spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    banner-mode: off

server:
  port: 8443
  ssl:
    key-store: classpath:academia.p12
    key-store-password: password
    key-password: password

logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG
        jdbc:
          core: TRACE

academia:
  jwt:
    secret: 52b1f28dbb6eff12e9e625f05df04a96bdae0190137c8b4e7507d3d283734577
    expirationInMs: 86400