spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    banner-mode: off

logging:
  level:
    root: warn
    org:
      springframework:
        security: DEBUG
        jdbc:
          core: TRACE

academia:
  jwt:
    secret: ======================academia=spring===========================
    expirationInMs: 86400