POST https://localhost:8443/api/v1/authenticate
content-type: application/json

{
    "username": "john",
    "password": "fun123"
}

###

GET https://localhost:8443/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huIiwicm9sZXMiOlsiUk9MRV9FTVBMT1lFRSJdLCJpYXQiOjE3MDI5ODk5OTMsImV4cCI6MTcwMzA3NjM5M30.o03SHoia-TAyV11WxJwfuXReo5jdJt_POARpdxwt3mg