POST https://localhost:8443/api/v1/authenticate
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET https://localhost:8443/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYXJ1c2giLCJyb2xlcyI6W10sImlhdCI6MTcwMzAxNDMzOCwiZXhwIjoxNzAzMTAwNzM4fQ.DgNjjVZy5YxMSM5bCLr8H-miClLsvUSuzsAr-pylz10

###

GET https://localhost:8443/api/v1/students
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzAzNTA3NTAyLCJleHAiOjE3MDM1OTM5MDJ9.hqwg3W2E7aSyscuGyt5EKSWQqrKk1AlVW6Ac6tRG4sg