POST https://localhost:8443/api/v1/authenticate
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET https://localhost:8443/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzA2NjQ2MDE0LCJleHAiOjE3MDY3MzI0MTR9.0wlgLRf0kbNpJvQ3VBpxVodT1Cwzdr6Kjg5DPtz4C5A

###

GET https://localhost:8443/api/v1/students
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzA2NjQ2MDE0LCJleHAiOjE3MDY3MzI0MTR9.0wlgLRf0kbNpJvQ3VBpxVodT1Cwzdr6Kjg5DPtz4C5A